[package]
name = "grinder"
version = "0.1.0"
authors = ["Zachary Moore <zcmoore@asu.edu>"]

[dependencies]
regex = "0.1.8"
getopts = "0.2.11"

[[bin]]
name = "grinder"
path = "src/rust/main.rs"
test = false
bench = false
doc = false
plugin = false
harness = false
